### ISSUE TITLE
Rename project to FINESSE

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/FINESSE_GUI#43]
I'm thinking that we don't really need the `_GUI` suffix on the name of everything, as there isn't a corresponding non-GUI version of FINESSE. It'd make things a bit terser.

What do you think @dalonsoa? It'd be easier to change at this stage than at a later date.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-122-27

**Comment by dalonsoa** [comment]
Yeah, I agree. Now it is better than later.
